import React, { useCallback } from "react";
import { useGetReport, useGenerateReport } from "@workspace/api-client-react";
import { Card, Button } from "@/components/ui";
import { FileText, Download, Play, CheckCircle, RefreshCw, BookOpen, TrendingUp, Target, MessageSquare } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";

function SectionIcon({ section }: { section: number }) {
  const icons = [BookOpen, TrendingUp, TrendingUp, Target, MessageSquare, CheckCircle];
  const Icon = icons[section - 1] ?? BookOpen;
  return <Icon className="w-4 h-4 text-primary shrink-0" />;
}

export function ReportView({ runId }: { runId: string }) {
  const { data, isLoading } = useGetReport(runId);
  const generateMutation = useGenerateReport();
  const queryClient = useQueryClient();

  const handleExportMarkdown = useCallback(() => {
    if (!data) return;

    const md = [
      `# Research Intelligence Dossier`,
      `**Topic:** ${data.topic}`,
      `**Run ID:** ${data.runId}`,
      `**Generated:** ${format(new Date(data.generatedAt), "MMMM dd, yyyy HH:mm")}`,
      `**Corpus Size:** ${data.totalPapers} papers`,
      "",
      "---",
      "",
      "## I. Executive Overview",
      "",
      data.overview,
      "",
      "## II. Network Topology",
      "",
      data.graphInsights,
      "",
      "## III. Temporal Trend Vectors",
      "",
      data.trendsSummary,
      "",
      "## IV. Identified Anomalies & Gaps",
      "",
      data.gapsSummary,
      "",
      "## V. Core Controversies",
      "",
      data.controversySummary,
      "",
      "## Strategic Recommendations",
      "",
      ...data.recommendations.map((r, i) => `${i + 1}. ${r}`),
      "",
      "---",
      "",
      `*Generated by Research Navigator — ${format(new Date(data.generatedAt), "yyyy-MM-dd")}*`,
    ].join("\n");

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-navigator-${data.runId.substring(0, 8)}-${data.topic.replace(/\s+/g, "-").toLowerCase().substring(0, 30)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [data]);

  if (isLoading) {
    return (
      <div className="h-64 flex items-center justify-center font-mono text-muted-foreground">
        <div className="flex items-center gap-3">
          <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          Compiling master dossier...
        </div>
      </div>
    );
  }

  const hasContent = data && data.totalPapers > 0;

  if (!hasContent) {
    return (
      <div className="flex flex-col items-center justify-center p-12 glass-panel rounded-lg text-center space-y-4 border border-dashed border-border">
        <FileText className="w-12 h-12 text-muted-foreground mb-2" />
        <h3 className="text-xl font-medium">Final Report Not Compiled</h3>
        <p className="text-muted-foreground text-sm max-w-md">
          Compile all generated insights into a final, exportable intelligence dossier. All prior analyses will be woven into a cohesive scientific report.
        </p>
        <div className="text-xs text-muted-foreground/60 font-mono mt-2 space-y-1 text-left max-w-xs">
          <p>Ensure you have completed:</p>
          <p>• Gap analysis (Anomalies tab)</p>
          <p>• Trend analysis (Vectors tab)</p>
          <p>• Debate session (Matrix tab)</p>
        </div>
        <Button
          variant="primary"
          onClick={() =>
            generateMutation.mutate({ runId }, {
              onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/report/${runId}`] }),
            })
          }
          disabled={generateMutation.isPending}
          className="font-mono mt-4"
        >
          {generateMutation.isPending ? (
            <><div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin mr-2" /> Compiling...</>
          ) : (
            <><Play className="w-4 h-4 mr-2" /> Generate Report</>
          )}
        </Button>
      </div>
    );
  }

  const sections = [
    { num: 1, title: "I. Executive Overview", content: data.overview },
    { num: 2, title: "II. Network Topology", content: data.graphInsights },
    { num: 3, title: "III. Temporal Trend Vectors", content: data.trendsSummary },
    { num: 4, title: "IV. Identified Anomalies & Gaps", content: data.gapsSummary },
    { num: 5, title: "V. Core Controversies", content: data.controversySummary },
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Document header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
        <div>
          <div className="font-mono text-primary text-xs uppercase tracking-widest mb-2">Intelligence Dossier</div>
          <h2 className="text-3xl font-bold tracking-tight text-foreground leading-tight">{data.topic}</h2>
          <div className="text-sm text-muted-foreground mt-2 font-mono flex flex-wrap gap-x-4 gap-y-1">
            <span>ID: {data.runId.split("-")[0]}</span>
            <span>Generated: {format(new Date(data.generatedAt), "MMM dd, yyyy HH:mm")}</span>
            <span>Corpus: {data.totalPapers} documents</span>
          </div>
        </div>
        <div className="flex gap-2 shrink-0">
          <Button
            variant="outline"
            size="sm"
            onClick={() =>
              generateMutation.mutate({ runId }, {
                onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/report/${runId}`] }),
              })
            }
            disabled={generateMutation.isPending}
            className="font-mono text-xs"
          >
            {generateMutation.isPending ? (
              <div className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin mr-1" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            )}
            Regenerate
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportMarkdown}
            className="font-mono text-xs"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" /> Export .md
          </Button>
        </div>
      </div>

      {/* Report card */}
      <Card className="bg-black/50 border-border shadow-2xl">
        <div className="p-8 sm:p-10 space-y-10 font-serif leading-relaxed">

          {sections.map(({ num, title, content }) => (
            <section key={num}>
              <h3 className="text-base font-mono font-bold uppercase tracking-widest text-primary mb-4 border-b border-primary/20 pb-2 flex items-center gap-2">
                <SectionIcon section={num} />
                {title}
              </h3>
              <p className="text-foreground/90 text-sm leading-8">{content}</p>
            </section>
          ))}

          {/* Recommendations */}
          {data.recommendations.length > 0 && (
            <section>
              <h3 className="text-base font-mono font-bold uppercase tracking-widest text-accent mb-4 border-b border-accent/20 pb-2 flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-accent shrink-0" />
                Strategic Recommendations
              </h3>
              <ol className="space-y-4 list-none">
                {data.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-4">
                    <span className="font-mono text-xs text-accent bg-accent/10 px-2 py-1 rounded shrink-0 mt-0.5">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="text-foreground/90 text-sm leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ol>
            </section>
          )}

        </div>

        {/* Footer */}
        <div className="border-t border-border/30 px-8 py-4 flex justify-between items-center">
          <span className="font-mono text-xs text-muted-foreground/60">
            Research Navigator Intelligence Platform
          </span>
          <span className="font-mono text-xs text-muted-foreground/60">
            {format(new Date(data.generatedAt), "yyyy-MM-dd")}
          </span>
        </div>
      </Card>
    </div>
  );
}
