import React, { useCallback } from "react";
import { useGetReport, useGenerateReport } from "@workspace/api-client-react";
import { Card, Button } from "@/components/ui";
import { FileText, Download, Play, CheckCircle, RefreshCw, BookOpen, TrendingUp, Target, MessageSquare, Code2, Printer } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";

function SectionIcon({ section }: { section: number }) {
  const icons = [BookOpen, TrendingUp, TrendingUp, Target, MessageSquare, CheckCircle];
  const Icon = icons[section - 1] ?? BookOpen;
  return <Icon className="w-4 h-4 text-muted-foreground shrink-0" />;
}

export function ReportView({ runId }: { runId: string }) {
  const { data, isLoading } = useGetReport(runId);
  const generateMutation = useGenerateReport();
  const queryClient = useQueryClient();

  const handleExportMarkdown = useCallback(() => {
    if (!data) return;

    const md = [
      `# Research Intelligence Dossier`,
      `**Topic:** ${data.topic}`,
      `**Run ID:** ${data.runId}`,
      `**Generated:** ${format(new Date(data.generatedAt), "MMMM dd, yyyy HH:mm")}`,
      `**Corpus Size:** ${data.totalPapers} papers`,
      "",
      "---",
      "",
      "## I. Executive Overview",
      "",
      data.overview,
      "",
      "## II. Network Topology",
      "",
      data.graphInsights,
      "",
      "## III. Temporal Trend Vectors",
      "",
      data.trendsSummary,
      "",
      "## IV. Identified Anomalies & Gaps",
      "",
      data.gapsSummary,
      "",
      "## V. Core Controversies",
      "",
      data.controversySummary,
      "",
      "## Strategic Recommendations",
      "",
      ...data.recommendations.map((r, i) => `${i + 1}. ${r}`),
      "",
      "---",
      "",
      `*Generated by Research Navigator — ${format(new Date(data.generatedAt), "yyyy-MM-dd")}*`,
    ].join("\n");

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-navigator-${data.runId.substring(0, 8)}-${data.topic.replace(/\s+/g, "-").toLowerCase().substring(0, 30)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [data]);

  const escapeHtml = (text: string): string =>
    text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");

  const handleExportHtml = useCallback(() => {
    if (!data) return;

    const sections = [
      { title: "I. Executive Overview", content: data.overview },
      { title: "II. Network Topology", content: data.graphInsights },
      { title: "III. Temporal Trend Vectors", content: data.trendsSummary },
      { title: "IV. Identified Anomalies & Gaps", content: data.gapsSummary },
      { title: "V. Core Controversies", content: data.controversySummary },
    ];

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Research Intelligence Dossier — ${escapeHtml(data.topic)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; background: #0a0a0f; color: #e8eaf0; line-height: 1.7; padding: 2rem; }
    .container { max-width: 820px; margin: 0 auto; }
    header { border-bottom: 1px solid #1e293b; padding-bottom: 2rem; margin-bottom: 3rem; }
    .label { font-family: 'Courier New', monospace; font-size: 0.65rem; text-transform: uppercase; letter-spacing: 0.2em; color: #a0a0a0; margin-bottom: 0.5rem; }
    h1 { font-size: 2.4rem; font-weight: 700; letter-spacing: -0.03em; color: #f1f5f9; margin-bottom: 0.75rem; }
    .meta { font-family: 'Courier New', monospace; font-size: 0.75rem; color: #64748b; display: flex; flex-wrap: wrap; gap: 1.5rem; margin-top: 0.5rem; }
    section { margin-bottom: 3rem; }
    h2 { font-family: 'Courier New', monospace; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.15em; color: #a0a0a0; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 0.5rem; margin-bottom: 1.25rem; }
    p { font-size: 0.95rem; color: #cbd5e1; }
    ol { padding-left: 1.5rem; }
    ol li { margin-bottom: 0.75rem; font-size: 0.95rem; color: #cbd5e1; }
    .rec-num { font-family: 'Courier New', monospace; font-size: 0.7rem; background: rgba(255,255,255,0.08); color: #e0e0e0; padding: 2px 6px; border-radius: 3px; margin-right: 0.5rem; }
    footer { border-top: 1px solid #1e293b; padding-top: 1rem; margin-top: 3rem; display: flex; justify-content: space-between; font-family: 'Courier New', monospace; font-size: 0.65rem; color: #475569; }
    @media print { body { background: #fff; color: #111; } h1, h2 { color: #111; } .meta, footer { color: #555; } p, ol li { color: #333; } }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="label">Intelligence Dossier</div>
      <h1>${escapeHtml(data.topic)}</h1>
      <div class="meta">
        <span>ID: ${escapeHtml(data.runId.split("-")[0] ?? "")}</span>
        <span>Generated: ${escapeHtml(format(new Date(data.generatedAt), "MMMM dd, yyyy HH:mm"))}</span>
        <span>Corpus: ${data.totalPapers} documents</span>
      </div>
    </header>
    ${sections.map(({ title, content }) => `
    <section>
      <h2>${escapeHtml(title)}</h2>
      <p>${escapeHtml(content)}</p>
    </section>`).join("")}
    ${data.recommendations.length > 0 ? `
    <section>
      <h2>Strategic Recommendations</h2>
      <ol style="list-style:none; padding:0;">
        ${data.recommendations.map((r, i) => `<li><span class="rec-num">${String(i + 1).padStart(2, "0")}</span>${escapeHtml(r)}</li>`).join("")}
      </ol>
    </section>` : ""}
    <footer>
      <span>Research Navigator Intelligence Platform</span>
      <span>${format(new Date(data.generatedAt), "yyyy-MM-dd")}</span>
    </footer>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-navigator-${data.runId.substring(0, 8)}-${data.topic.replace(/\s+/g, "-").toLowerCase().substring(0, 30)}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [data]);

  const handleExportPdf = useCallback(() => {
    if (!data) return;

    const sections = [
      { title: "I. Executive Overview", content: data.overview },
      { title: "II. Network Topology", content: data.graphInsights },
      { title: "III. Temporal Trend Vectors", content: data.trendsSummary },
      { title: "IV. Identified Anomalies & Gaps", content: data.gapsSummary },
      { title: "V. Core Controversies", content: data.controversySummary },
    ];

    const printHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Research Intelligence Dossier — ${escapeHtml(data.topic)}</title>
  <style>
    @page { size: A4; margin: 2cm 2.5cm; }
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; color: #111; line-height: 1.75; font-size: 11pt; }
    .container { max-width: 100%; }
    header { border-bottom: 2px solid #111; padding-bottom: 1.5rem; margin-bottom: 2rem; }
    .label { font-family: 'Courier New', monospace; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.2em; color: #666; margin-bottom: 0.5rem; }
    h1 { font-size: 22pt; font-weight: 700; letter-spacing: -0.02em; color: #111; margin-bottom: 0.5rem; }
    .meta { font-family: 'Courier New', monospace; font-size: 8pt; color: #666; display: flex; gap: 1.5rem; }
    section { margin-bottom: 2rem; page-break-inside: avoid; }
    h2 { font-family: 'Courier New', monospace; font-size: 9pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: #333; border-bottom: 1px solid #ccc; padding-bottom: 4pt; margin-bottom: 10pt; }
    p { font-size: 11pt; color: #222; margin-bottom: 8pt; text-align: justify; }
    ol { padding-left: 1.2rem; }
    ol li { margin-bottom: 8pt; font-size: 11pt; color: #222; }
    .rec-num { font-family: 'Courier New', monospace; font-size: 8pt; background: #eee; color: #333; padding: 1px 5px; border-radius: 2px; margin-right: 6px; }
    footer { border-top: 1px solid #ccc; padding-top: 8pt; margin-top: 2rem; display: flex; justify-content: space-between; font-family: 'Courier New', monospace; font-size: 7pt; color: #999; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="label">Research Intelligence Dossier</div>
      <h1>${escapeHtml(data.topic)}</h1>
      <div class="meta">
        <span>ID: ${escapeHtml(data.runId.split("-")[0] ?? "")}</span>
        <span>Generated: ${escapeHtml(format(new Date(data.generatedAt), "MMMM dd, yyyy HH:mm"))}</span>
        <span>Corpus: ${data.totalPapers} documents</span>
      </div>
    </header>
    ${sections.map(({ title, content }) => `
    <section>
      <h2>${escapeHtml(title)}</h2>
      <p>${escapeHtml(content)}</p>
    </section>`).join("")}
    ${data.recommendations.length > 0 ? `
    <section>
      <h2>Strategic Recommendations</h2>
      <ol style="list-style:none; padding:0;">
        ${data.recommendations.map((r, i) => `<li><span class="rec-num">${String(i + 1).padStart(2, "0")}</span>${escapeHtml(r)}</li>`).join("")}
      </ol>
    </section>` : ""}
    <footer>
      <span>Research Navigator Intelligence Platform</span>
      <span>${format(new Date(data.generatedAt), "yyyy-MM-dd")}</span>
    </footer>
  </div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(printHtml);
      printWindow.document.close();
    }
  }, [data]);

  if (isLoading) {
    return (
      <div className="h-64 flex items-center justify-center font-mono text-muted-foreground">
        <div className="flex items-center gap-3">
          <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
          Compiling master dossier...
        </div>
      </div>
    );
  }

  const hasContent = data && data.totalPapers > 0;

  if (!hasContent) {
    return (
      <div className="flex flex-col items-center justify-center p-12 panel rounded text-center space-y-4 border-dashed border-border">
        <FileText className="w-12 h-12 text-muted-foreground mb-2" />
        <h3 className="text-xl font-medium">Final Report Not Compiled</h3>
        <p className="text-muted-foreground text-sm max-w-md">
          Compile all generated insights into a final, exportable intelligence dossier. All prior analyses will be woven into a cohesive scientific report.
        </p>
        <div className="text-xs text-muted-foreground/60 font-mono mt-2 space-y-1 text-left max-w-xs">
          <p>Ensure you have completed:</p>
          <p>• Gap analysis (Anomalies tab)</p>
          <p>• Trend analysis (Vectors tab)</p>
          <p>• Debate session (Matrix tab)</p>
        </div>
        <Button
          variant="primary"
          onClick={() =>
            generateMutation.mutate({ runId }, {
              onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/report/${runId}`] }),
            })
          }
          disabled={generateMutation.isPending}
          className="font-mono mt-4"
        >
          {generateMutation.isPending ? (
            <><div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin mr-2" /> Compiling...</>
          ) : (
            <><Play className="w-4 h-4 mr-2" /> Generate Report</>
          )}
        </Button>
      </div>
    );
  }

  const sections = [
    { num: 1, title: "I. Executive Overview", content: data.overview },
    { num: 2, title: "II. Network Topology", content: data.graphInsights },
    { num: 3, title: "III. Temporal Trend Vectors", content: data.trendsSummary },
    { num: 4, title: "IV. Identified Anomalies & Gaps", content: data.gapsSummary },
    { num: 5, title: "V. Core Controversies", content: data.controversySummary },
  ];

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Document header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
        <div>
          <div className="font-mono text-muted-foreground text-xs uppercase tracking-widest mb-2">Intelligence Dossier</div>
          <h2 className="text-3xl font-bold tracking-tight text-foreground leading-tight">{data.topic}</h2>
          <div className="text-sm text-muted-foreground mt-2 font-mono flex flex-wrap gap-x-4 gap-y-1">
            <span>ID: {data.runId.split("-")[0]}</span>
            <span>Generated: {format(new Date(data.generatedAt), "MMM dd, yyyy HH:mm")}</span>
            <span>Corpus: {data.totalPapers} documents</span>
          </div>
        </div>
        <div className="flex gap-2 shrink-0">
          <Button
            variant="outline"
            size="sm"
            onClick={() =>
              generateMutation.mutate({ runId }, {
                onSuccess: () => queryClient.invalidateQueries({ queryKey: [`/api/report/${runId}`] }),
              })
            }
            disabled={generateMutation.isPending}
            className="font-mono text-xs"
          >
            {generateMutation.isPending ? (
              <div className="w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full animate-spin mr-1" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            )}
            Regenerate
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportMarkdown}
            className="font-mono text-xs"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" /> Export .md
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportHtml}
            className="font-mono text-xs"
          >
            <Code2 className="w-3.5 h-3.5 mr-1.5" /> Export .html
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportPdf}
            className="font-mono text-xs"
          >
            <Printer className="w-3.5 h-3.5 mr-1.5" /> Export PDF
          </Button>
        </div>
      </div>

      {/* Report card */}
      <Card className="bg-card border-border">
        <div className="p-8 sm:p-10 space-y-10 font-serif leading-relaxed">

          {sections.map(({ num, title, content }) => (
            <section key={num}>
              <h3 className="text-base font-mono font-bold uppercase tracking-widest text-muted-foreground mb-4 border-b border-border pb-2 flex items-center gap-2">
                <SectionIcon section={num} />
                {title}
              </h3>
              <p className="text-foreground/90 text-sm leading-8">{content}</p>
            </section>
          ))}

          {/* Recommendations */}
          {data.recommendations.length > 0 && (
            <section>
              <h3 className="text-base font-mono font-bold uppercase tracking-widest text-muted-foreground mb-4 border-b border-border pb-2 flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-muted-foreground shrink-0" />
                Strategic Recommendations
              </h3>
              <ol className="space-y-4 list-none">
                {data.recommendations.map((rec, i) => (
                  <li key={i} className="flex items-start gap-4">
                    <span className="font-mono text-xs text-muted-foreground bg-secondary px-2 py-1 rounded shrink-0 mt-0.5">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <span className="text-foreground/90 text-sm leading-relaxed">{rec}</span>
                  </li>
                ))}
              </ol>
            </section>
          )}

        </div>

        {/* Footer */}
        <div className="border-t border-border/30 px-8 py-4 flex justify-between items-center">
          <span className="font-mono text-xs text-muted-foreground/60">
            Research Navigator Intelligence Platform
          </span>
          <span className="font-mono text-xs text-muted-foreground/60">
            {format(new Date(data.generatedAt), "yyyy-MM-dd")}
          </span>
        </div>
      </Card>
    </div>
  );
}
